Repository spring-financial-group/terraform-jx-azure, pull requests merged in 2025-07, with the labels that each got.

#156 chore: soft delete retention
  cluster/terraform-jx-azurekeyvault/main.tf
Labels: size/XS, approved

#157 commit: build llm node pool
  cluster/main.tf
  cluster/terraform-jx-cluster-aks/cluster/main.tf
  cluster/terraform-jx-cluster-aks/cluster/variables.tf
  cluster/terraform-jx-cluster-aks/main.tf
  cluster/terraform-jx-cluster-aks/variables.tf
  cluster/variables.tf
  main.tf
  values.auto.tfvars
  variables.tf
Labels: size/L, approved

#159 chore: Upgrade ACR to premium tier
  cluster/terraform-jx-cluster-aks/cluster/main.tf
  cluster/terraform-jx-registry-acr/main.tf
Labels: size/M, approved

#160 chore: build llm node pool
  cluster/terraform-jx-cluster-aks/cluster/main.tf
  values.auto.tfvars
Labels: size/M, approved

#161 chore: remove llm node pool
  cluster/terraform-jx-cluster-aks/cluster/main.tf
Labels: size/M, approved

#166 chore: add node pool with llm node label
  cluster/terraform-jx-cluster-aks/cluster/main.tf
Labels: size/M, approved

#168 chore: create llm node pool with additional taint
  cluster/terraform-jx-cluster-aks/cluster/main.tf
Labels: size/M, approved

#169 chore: increase max node count llm
  values.auto.tfvars
Labels: size/XS, approved
